<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Caring & Co.</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />
    <link rel="stylesheet" href="./fontawesome/css/all.css" media="screen" type="text/css" />
    <link rel="stylesheet" href="./styles/style.css" media="screen" type="text/css" />
</head>

<body>    
    <div class="landing">
        <div class="navbar">
            <div class="logo">
                <p style="color:#725ac1;font-size:2rem;"><i class="fas fa-heartbeat"></i><b> Caring &amp; Co.</b></p>
            </div>
            <div class="links">
                <a href="#working" class="link">Working</a>
                <a href="#features" class="link">Features</a>
                <a href="#contact" class="link">Contact</a>
                <a href="./login.php" class="special">Login</a>
            </div>
        </div>
        <div class="banner">
            <div class="box">
                <h3>Simple, Efficient,<br />Seamless</h3>
                <br /><br />
                <p>A tool to provide doctors with the power of Deep Learning and obtain high accuracy results to analyse a patient's health in a better way.</p>
            </div>
        </div>
    </div>
    
    <div class="working-holder" id="working">
        <div class="row">
            <h3>How This Works</h3>
            <br /><br /><br />
            <div class="working">
                <div class="container left">
                    <div class="content">
                        <h2><i class="fas fa-cookie-bite"></i>Feed the data</h2>
                        <br />
                        <p>
                            Datasets generated by ECG machine, are fed into the neural network machine and sent for initial refinement of the raw signal.
                        </p>
                    </div>
                </div>
                <div class="container right">
                    <div class="content">
                        <h2><i class="fas fa-microchip"></i>Process the data</h2>
                        <br />
                        <p>
                            The noise in the signal is removed in the pre-processing stage, resulting in a well refined dataset.
                        </p>
                    </div>
                </div>
                <div class="container left">
                    <div class="content">
                        <h2><i class="fab fa-react"></i>Predicting the result</h2>
                        <br />
                        <p>
                            Neural Networks use Deep Learning as a mode for the analysis of the refined dataset in the form of image classification.
                        </p>
                    </div>
                </div>
                <div class="container right">
                    <div class="content">
                        <h2><i class="fas fa-chart-line"></i>Create an analysis</h2>
                        <br />
                        <p>
                            An analysis graph consisting of FHR and UC is designed based on the highly accurate predictions made by the neural network.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="features" id="features">
        <div class="row">
            <div class="col">
                <i class="fas fa-keyboard"></i>
                <h5>Simple UI</h5>
                <br />
                <p>
                    We provide simple, unique and smooth User Interface to the doctors.
                </p>
            </div>
            <div class="col">
                <i class="fas fa-users"></i>
                <h5>Patient Report</h5>
                <br />
                <p>
                    You can turn the analysis into an Image report for the patient to keep the report handy.
                </p>
            </div>
            <div class="col">
                <i class="fas fa-brain"></i>
                <h5>Accurate AI</h5>
                <br />
                <p>We use accurate and faster AIs in our modern systems to provide doctors with great precision.</p>
            </div>
            <div class="col">
                <i class="fas fa-users"></i>
                <h5>Multiple Patients</h5>
                <br />
                <p>
                    Keep a record of all patients analysed by a doctor in a single place.
                </p>
            </div>
        </div>
    </div>

    <div class="footer" id="contact">
        <div class="row">
            <div class="social">
                <a href="https://facebook.com" target="_blank"><i class="fab fa-facebook"></i></a>
                <a href="https://twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
                <a href="https://instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
            </div>
            <div class="info">
                <p>Designed by Flash Coders</p>
            </div>
        </div>
    </div>
</body>
</html>